# Generated by Django 4.0 on 2022-01-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('university', models.CharField(max_length=100)),
                ('cgpa', models.FloatField(max_length=4)),
                ('ielts', models.FloatField(max_length=4)),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
    ]
