# Generated by Django 4.0.1 on 2022-01-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alberta_calgary_carleton_mcgill_queens_windsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alberta',
        ),
        migrations.DeleteModel(
            name='Boston',
        ),
        migrations.DeleteModel(
            name='Calgary',
        ),
        migrations.DeleteModel(
            name='California',
        ),
        migrations.DeleteModel(
            name='Carleton',
        ),
        migrations.DeleteModel(
            name='Dalhousie',
        ),
        migrations.DeleteModel(
            name='Massachusetts',
        ),
        migrations.DeleteModel(
            name='Mcgill',
        ),
        migrations.DeleteModel(
            name='Northeastern',
        ),
        migrations.DeleteModel(
            name='Ontariotech',
        ),
        migrations.DeleteModel(
            name='Pennsylvania',
        ),
        migrations.DeleteModel(
            name='Princeton',
        ),
        migrations.DeleteModel(
            name='Queens',
        ),
        migrations.DeleteModel(
            name='Stanford',
        ),
        migrations.DeleteModel(
            name='Texas',
        ),
        migrations.DeleteModel(
            name='Toronto',
        ),
        migrations.DeleteModel(
            name='Verginia',
        ),
        migrations.DeleteModel(
            name='Windsor',
        ),
    ]
